name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm run make:docs
        git config --global user.name "Seniru"
        git config --global user.email "senirupasan@gmail.com"
        git add .
        git status
        git commit -m "chore: Build"
        git push origin HEAD:master

      env:
        CI: true
